import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Suspense } from 'react'

import TopBar from "./top-bar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  modal,
}: Readonly<{
  children: React.ReactNode;
  modal: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="flex flex-col min-h-screen">
          <TopBar />
          <main className="flex-grow pt-20">
            <Suspense>
            {children}
            </Suspense>
          </main>
        </div>
        <Suspense>

        {modal}
        </Suspense>
      </body>
    </html>
  );
}
